#!/bin/bash

# from the book Sed Awk O'REILLY Dale Dougherty and Arnold Robbins 

#  Sorts name by states and lists the name of the state followed by the name of each person residing in that state.

awk -F, '{
	print $4 ", " $0
}' $* |
sort |
awk -F, '
$1 == LastState {
	print "\t" $2
} 

$1 != LastState {
	  LastState = $1  
	  print $1
	  print "\t" $2

}' # $ != LastState, - prints the name of the state followed by the persons name

# if it is the same then only the person's name is printed.
# Note that we don't have to assign to a variable before using it, awk variables are initialized to the empty string
